In [1]:
import numpy as np

In [4]:
m = np.asarray([[.8,.3],[.2,.7]])

In [7]:
s = np.asarray([1,0])
for i in range(10):
    s= m@s
    print(s)

[0.8 0.2]
[0.7 0.3]
[0.65 0.35]
[0.625 0.375]
[0.6125 0.3875]
[0.60625 0.39375]
[0.603125 0.396875]
[0.6015625 0.3984375]
[0.60078125 0.39921875]
[0.60039063 0.39960938]


In [8]:
m@np.asarray([.6,.4])

array([0.6, 0.4])

In [9]:
E = np.asarray([[1,0,0,0],[0,1,0,0],[0,-1,1,0],[0,1,-2,1]])

In [10]:
M = np.asarray([[1,0,0,0],[0,1,0,0],[0,1,1,0],[0,1,2,1]])

In [11]:
E@M

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [12]:
E1 = np.asarray([[1,0,0,0],[-1,1,0,0],[0,-1,1,0],[0,0,-1,1]])

In [14]:
E@E1

array([[ 1,  0,  0,  0],
       [-1,  1,  0,  0],
       [ 1, -2,  1,  0],
       [-1,  3, -3,  1]])